### ISSUE TITLE
Cache directory does not exist 

### ISSUE THREAD

**Issue by DrMurgz** [dtech-auto/porpo#7]
This is what I'm getting.

C:\Users\james\Desktop\GitHub\porpo\scripts>python gui.py
Traceback (most recent call last):
  File "C:\Users\james\Desktop\GitHub\porpo\scripts\gui.py", line 9, in <module>
    class Dirs():
  File "C:\Users\james\Desktop\GitHub\porpo\scripts\gui.py", line 28, in Dirs
    fastf1.Cache.enable_cache(cache_path)
  File "C:\Users\james\AppData\Local\Programs\Python\Python310\lib\site-packages\fastf1\api.py", line 133, in enable_cache
    raise NotADirectoryError("Cache directory does not exist! Please check for typos or create it first.")
NotADirectoryError: Cache directory does not exist! Please check for typos or create it first.

C:\Users\james\Desktop\GitHub\porpo\scripts>python main.py
Traceback (most recent call last):
  File "C:\Users\james\Desktop\GitHub\porpo\scripts\main.py", line 8, in <module>
    fastf1.Cache.enable_cache('venv/F1/Cache/')
  File "C:\Users\james\AppData\Local\Programs\Python\Python310\lib\site-packages\fastf1\api.py", line 133, in enable_cache
    raise NotADirectoryError("Cache directory does not exist! Please check for typos or create it first.")
NotADirectoryError: Cache directory does not exist! Please check for typos or create it first.

**Comment by dtech-auto** [comment]
I fixed this issue, try the nightly or stable!
